// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GastosPersonales.API.Migrations
{
    [DbContext(typeof(GastosPersonalesAPIContext))]
    partial class GastosPersonalesAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GastosPersonales.Modelos.Categoria", b =>
                {
                    b.Property<int>("idCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCategoria"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("idCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("GastosPersonales.Modelos.Movimiento", b =>
                {
                    b.Property<int>("idMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idMovimiento"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.Property<int>("idCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer");

                    b.Property<double>("monto")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("idMovimiento");

                    b.HasIndex("idCategoria");

                    b.HasIndex("idUsuario");

                    b.ToTable("Movimiento");
                });

            modelBuilder.Entity("GastosPersonales.Modelos.Presupuesto", b =>
                {
                    b.Property<int>("idPresupuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_presupuesto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idPresupuesto"));

                    b.Property<int>("anio")
                        .HasColumnType("integer");

                    b.Property<int>("idCategoria")
                        .HasColumnType("integer");

                    b.Property<int>("idUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("mes")
                        .HasColumnType("integer");

                    b.Property<double>("montoLimite")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_limite");

                    b.HasKey("idPresupuesto");

                    b.HasIndex("idCategoria");

                    b.HasIndex("idUsuario");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("GastosPersonales.Modelos.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GastosPersonales.Modelos.Movimiento", b =>
                {
                    b.HasOne("GastosPersonales.Modelos.Categoria", "Categoria")
                        .WithMany("Movimientos")
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GastosPersonales.Modelos.Usuario", "Usuario")
                        .WithMany("Movimientos")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GastosPersonales.Modelos.Presupuesto", b =>
                {
                    b.HasOne("GastosPersonales.Modelos.Categoria", "Categoria")
                        .WithMany("Presupuestos")
                        .HasForeignKey("idCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GastosPersonales.Modelos.Usuario", "Usuario")
                        .WithMany("Presupuestos")
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GastosPersonales.Modelos.Categoria", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("GastosPersonales.Modelos.Usuario", b =>
                {
                    b.Navigation("Movimientos");

                    b.Navigation("Presupuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
